name: CI

on:
- push
- pull_request
- workflow_dispatch

jobs:
  main:
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, '3.10', '3.11']
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python }}
    steps:
    - uses: actions/checkout@v3
    - name: set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: update PIP
      run:
        python -m pip install --upgrade pip
    - name: install wheel
      run:
        python -m pip install --upgrade wheel
    - name: install package
      run:
        python -m pip install .[dev]
    - name: run tests
      run: |
        cd tests
        python -m unittest discover --verbose --start-directory .
        cd ..
    - name: run flake8
      run:
        python -m flake8 .
